export const ROUTES = {
  home: "/",
  search: "/ara",
  cart: "/sepet",
  checkout: "/odeme",
  login: "/giris",
  register: "/kayit",
  account: "/hesabim",
  orders: "/siparisler",
  favorites: "/favoriler",
  addresses: "/adresler",
  about: "/hakkimizda",
  contact: "/iletisim",
  faq: "/sss",
  blog: "/blog",
  privacy: "/gizlilik",
  terms: "/kosullar",
  category: (slug: string) => `/kategori/${slug}`,
  product: (slug: string) => `/urun/${slug}`,
  blogPost: (slug: string) => `/blog/${slug}`,
} as const;

export const LABELS = {
  appName: "Talazan Mağaza",
  home: "Ana Sayfa",
  search: "Ara",
  searchPlaceholder: "Ürün, kategori veya marka ara...",
  cart: "Sepet",
  checkout: "Ödeme",
  login: "Giriş Yap",
  register: "Kayıt Ol",
  logout: "Çıkış Yap",
  account: "Hesabım",
  orders: "Siparişlerim",
  favorites: "Favorilerim",
  addresses: "Adreslerim",
  profile: "Profil",
  about: "Hakkımızda",
  contact: "İletişim",
  faq: "Sık Sorulan Sorular",
  blog: "Blog",
  privacy: "Gizlilik Politikası",
  terms: "Kullanım Koşulları",
  addToCart: "Sepete Ekle",
  buyNow: "Hemen Al",
  outOfStock: "Stokta Yok",
  inStock: "Stokta Var",
  total: "Toplam",
  subtotal: "Ara Toplam",
  shipping: "Kargo",
  freeShipping: "Ücretsiz Kargo",
  continueShopping: "Alışverişe Devam Et",
  proceedToCheckout: "Ödemeye Geç",
  emptyCart: "Sepetiniz boş",
  emptyFavorites: "Henüz favori ürününüz yok",
  emptyOrders: "Henüz siparişiniz yok",
  loading: "Yükleniyor...",
  error: "Bir hata oluştu",
  retry: "Tekrar Dene",
  save: "Kaydet",
  cancel: "İptal",
  delete: "Sil",
  edit: "Düzenle",
  viewAll: "Tümünü Gör",
  featuredProducts: "Öne Çıkan Ürünler",
  categories: "Kategoriler",
  brands: "Markalar",
  newArrivals: "Yeni Gelenler",
  bestSellers: "Çok Satanlar",
  discountedProducts: "İndirimli Ürünler",
  trendingProducts: "Trend Ürünler",
  recommendedProducts: "Sizin İçin Önerilenler",
  flashSale: "Flaş İndirim",
  freeShippingBanner: "1500 TL ve üzeri siparişlerde ücretsiz kargo",
  orderTracking: "Sipariş Takibi",
  helpCenter: "Yardım Merkezi",
  allCategories: "Tüm Kategoriler",
  quickView: "Hızlı Bak",
  compare: "Karşılaştır",
  installment: "taksit",
  newBadge: "Yeni",
  discountBadge: "İndirim",
  originalProduct: "Orijinal Ürün",
  fastDelivery: "Hızlı Teslimat",
  securePayment: "Güvenli Ödeme",
  easyReturns: "Kolay İade",
  support247: "7/24 Destek",
  paymentMethods: "Ödeme Yöntemleri",
  shippingPartners: "Kargo Firmaları",
  mobileApps: "Mobil Uygulamalar",
  corporate: "Kurumsal",
  customerService: "Müşteri Hizmetleri",
  newsletter: "Bülten",
  newsletterDesc: "Kampanya ve yeniliklerden haberdar olun.",
  subscribe: "Abone Ol",
  email: "E-posta",
  password: "Şifre",
  firstName: "Ad",
  lastName: "Soyad",
  phone: "Telefon",
  address: "Adres",
  city: "İl",
  district: "İlçe",
  neighborhood: "Mahalle",
  postalCode: "Posta Kodu",
  orderSuccess: "Siparişiniz alındı",
  orderNumber: "Sipariş No",
  darkMode: "Karanlık Mod",
  lightMode: "Aydınlık Mod",
  notFound: "Sayfa bulunamadı",
  backToHome: "Ana Sayfaya Dön",
  filters: "Filtreler",
  sortBy: "Sırala",
  priceRange: "Fiyat Aralığı",
  onlyInStock: "Sadece stokta olanlar",
  results: "sonuç",
  noResults: "Sonuç bulunamadı",
  productDetails: "Ürün Detayları",
  description: "Açıklama",
  sku: "Stok Kodu",
  brand: "Marka",
  category: "Kategori",
  relatedProducts: "Benzer Ürünler",
  defaultAddress: "Varsayılan Adres",
  addAddress: "Adres Ekle",
  updateProfile: "Profili Güncelle",
  welcomeBack: "Tekrar hoş geldiniz",
  createAccount: "Hesap oluştur",
  alreadyHaveAccount: "Zaten hesabınız var mı?",
  dontHaveAccount: "Hesabınız yok mu?",
  contactUs: "Bize Ulaşın",
  sendMessage: "Mesaj Gönder",
  message: "Mesajınız",
  subject: "Konu",
} as const;

export const SORT_OPTIONS = [
  { value: "isim,asc", label: "İsim (A-Z)" },
  { value: "isim,desc", label: "İsim (Z-A)" },
  { value: "satisTutari,asc", label: "Fiyat (Artan)" },
  { value: "satisTutari,desc", label: "Fiyat (Azalan)" },
] as const;

export const DEFAULT_PAGE_SIZE = 12;

export const PAGE_SLUGS = {
  about: "hakkimizda",
  contact: "iletisim",
  faq: "sss",
  privacy: "gizlilik",
  terms: "kosullar",
  blog: "blog",
} as const;

export const AUTH_STORAGE_KEY = "talazan-site-auth";
export const CART_STORAGE_KEY = "talazan-site-cart";
export const ORDERS_STORAGE_KEY = "talazan-site-orders";
